name: macos

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        LCG: ["dev3/arm64-mac13-clang150-opt",
              "dev4/arm64-mac15-clang160-opt "]
    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v5.0
    - uses: aidasoft/run-lcg-view@v4
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          echo "::group::Run CMake"
          export JULIA_DEPOT_PATH="$(mktemp -d -p /tmp -t julia_depot_XXXXX):"
          mkdir build install
          cd build
          cmake -DENABLE_SIO=ON \
            -DENABLE_JULIA=ON \
            -DENABLE_DATASOURCE=ON \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror -Wno-error=deprecated-declarations " \
            -DUSE_EXTERNAL_CATCH2=OFF \
            -DPODIO_SET_RPATH=ON \
            -DENABLE_RNTUPLE=ON \
            -G Ninja ..
          echo "::endgroup::"
          echo "::group::Build"
          ninja -k0
          echo "::endgroup"
          echo "::group::Julia StaticArrays Package Install"
          julia -e 'import Pkg; Pkg.add("StaticArrays")'
          echo "::endgroup"
          echo "::group::Run tests"
          ctest --output-on-failure
          echo "::endgroup::"
          echo "::group::Install"
          ninja install
          echo "::endgroup::"
